### ISSUE TITLE
Add configuration for Assay field

### ISSUE THREAD

**Issue by dosumis** [kharchenkolab/cap-pipeline-config#10]
This can be done with a list of EFO assay terms.  Check suggested terms on Confluence / confirm with Evan.

**Comment by bvarner-ebi** [comment]
Referring to https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#assay_ontology_term_id, there are two recommended terms mentioned that are not yet included in the boosted Assay list, namely:

10x 5' v1	["EFO:0011025"](http://www.ebi.ac.uk/efo/EFO_0011025)
Smart-seq2	["EFO:0008931"](http://www.ebi.ac.uk/efo/EFO_0008931)

Reopening ticket to add these.
