### ISSUE TITLE
Ethnicity field issue

### ISSUE THREAD

**Issue by ubyndr** [kharchenkolab/cap-pipeline-config#29]
We are using following SPARQL query to add 'Race' tags:

```
PREFIX inSubset: <http://www.geneontology.org/formats/oboInOwl#inSubset>


CONSTRUCT {
  ?s <http://n2o.neo/property/nodeLabel> "Race" .
}
WHERE 
{
      ?s inSubset: <http://purl.obolibrary.org/obo/NCIT_C128689> .
}
```

David suggested us to use HANCESTRO ontology for races. 

We cannot retrieve anything from HANCESTRO with the SPARQL query.

- We should either change the SPARQL query or
- Use an other ontology that contains http://purl.obolibrary.org/obo/NCIT_C128689 class

**Comment by dosumis** [comment]
> We cannot retrieve anything from HANCESTRO with the SPARQL query.

Not sure why you would expect to.

The main reason to use HANCESTRO is for alignment with HCA and CZI standards.  For that you need to specify subclasses of [ancestry category](https://www.ebi.ac.uk/ols/ontologies/hancestro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHANCESTRO_0004&viewMode=All&siblings=false).  Can be done easily in the YAML config.  SPARQL with transitivity of subClassOf will likely give you the same result.

**Comment by ubyndr** [comment]
> > We cannot retrieve anything from HANCESTRO with the SPARQL query.
> 
> Not sure why you would expect to.

I was looking at HANCESTRO with protege and I couldn't find NCIT_C128689 class in it, which is a normal thing. So we will use DL instead of SPARQL as you described.

```
  - classes:
      - HANCESTRO:0004 
    label: Race
```
