### ISSUE TITLE
write_organ_tags.py script should produce a simple dictionary lookup of organ ID to semantic_tag, saved to YAML

### ISSUE THREAD

**Issue by dosumis** [kharchenkolab/cap-pipeline-config#34]
ID should be IRI or Curie.  co-ordinate with @ubyndr 

e.g. 
```YAML
 "UBERON:0002113" : Kidney_cell
```

This lookup is required in order for the API to return a semantic tag for boosting the cell field, depending on organ chosen.

**Comment by bvarner-ebi** [comment]
@dosumis, @ubyndr, is this a request to consolidate what is done [here](https://github.com/kharchenkolab/cap-ontology-search/issues/14) into the write_organ_tags.py script?

**Comment by ubyndr** [comment]
We should discuss what to use, http://purl.obolibrary.org/obo/UBERON_0003644 or UBERON:0003644. I have made the changes in search service based on UBERON:0003644. It is ok for now. I've also talked with CAP developers today and they also didn't have any objection. Using IRIs **might be** easier for them but we are not sure at the moment :)
Long story short, we can keep it as it is at the moment.

**Comment by dosumis** [comment]
> @dosumis, @ubyndr, is this a request to consolidate what is done https://github.com/kharchenkolab/cap-ontology-search/issues/14 into the write_organ_tags.py script?

Sorry - had forgotten we'd made a ticket for this on the other repo.  OK to keep separate (although not strictly DRY as we may need to change the way we build the organ list).
