### ISSUE TITLE
Make sure all CURIE prefixes required for class expressions are in place

### ISSUE THREAD

**Issue by dosumis** [kharchenkolab/cap-pipeline-config#40]
Add here: https://github.com/kharchenkolab/cap-pipeline-config/blob/development/config/prod/neo4j2owl-config.yaml#L33

Needed:
*  HANCESTRO:
* EFO (turns out we also need to add CURIEs for sparql configs)
* PATO

**Comment by ubyndr** [comment]
`HANCESTRO: http://purl.obolibrary.org/obo/HANCESTRO_` has been added to neo4j2owl-config.yaml

**Comment by ubyndr** [comment]
```
  EFO: http://www.ebi.ac.uk/efo/EFO_
  PATO: http://purl.obolibrary.org/obo/PATO_
```
has been added to neo4j2owl-config.yaml
