### ISSUE TITLE
Add configuration for Disease field

### ISSUE THREAD

**Issue by bvarner-ebi** [kharchenkolab/cap-pipeline-config#43]
Leveraging [MONDO](https://www.ebi.ac.uk/ols/ontologies/mondo), add a DL query to neo4j2owl.yaml to filter on MONDO_0000001 'disease or disorder'.

**Comment by ubyndr** [comment]
Solr indexes are missing Disease tags, we should look for the root cause

**Comment by ubyndr** [comment]
It seems there was a typo in where the dumps pipeline reads the yaml config.
