### ISSUE TITLE
Refine list of organs used for semantic tags 

### ISSUE THREAD

**Issue by bvarner-ebi** [kharchenkolab/cap-pipeline-config#46]
Currently [generate_organ_tags.py ](https://github.com/kharchenkolab/cap-pipeline-config/blob/main/config/collectdata/python/generate_organ_tags.py) pulls all organ/tissue terms from the Uberon organ_slim as a basis for assigning 'organ' semantic tags that will be used to filter/boost search suggestions in the Cell Annotation Platform. We are considering ways to refine this list of organ terms.

One option is to leverage [tissue_dict.json](https://github.com/kharchenkolab/cap-data-clean-up/blob/devel/datasets_description/tissue_dict.json). Currently this list has 929 organ/tissue terms mapped to 106 more general terms. As a start, I mapped the more general terms to mostly UBERON CURIEs (+ a couple CL CURIEs). That work can be reviewed here: [OrganList](https://docs.google.com/spreadsheets/d/1QzuB07M61TqCElRzydWVs4ap5RIIlmg7xIpSLxC6PFU/edit#gid=272982245).

For further discussion:

[ ] Do we want to continue using the organ_slim from Uberon to generate semantic tags for CAP search suggestions?

[ ] Alternatively, do we want to use the manually curated [tissue_dict.json](https://github.com/kharchenkolab/cap-data-clean-up/blob/devel/datasets_description/tissue_dict.json)? If so, do we want to limit it to the more general terms (~ 90) or the more specific terms (~ 900)?

FYI, @ubyndr, @dosumis, @evanbiederstedt, @mfutey.

**Comment by bvarner-ebi** [comment]
FYI @arapoff

**Comment by arapoff** [comment]
[tissue_dict.json](https://github.com/kharchenkolab/cap-data-clean-up/blob/devel/datasets_description/tissue_dict.json) seems effective. So I think we just need to enrich it with relationships as we move forward

**Comment by bvarner-ebi** [comment]
Thanks for the feedback, @arapoff.

To discuss with @dosumis and @ubyndr:
- if we switch to using [tissue_dict.json](https://github.com/kharchenkolab/cap-data-clean-up/blob/devel/datasets_description/tissue_dict.json) instead of organ_slim, will it be hard-coded or pulled from the the tissue_dict.json file? Will it be the general list (already mapped to uberon [here- OrganList](https://docs.google.com/spreadsheets/d/1QzuB07M61TqCElRzydWVs4ap5RIIlmg7xIpSLxC6PFU/edit#gid=272982245)) or the more specific list of > 900 terms?

**Comment by dosumis** [comment]
Decisions:

1. Move to using list from CAP organList (the list of 90+ general terms in tissue_dict.json)  for now.
2. Generate reports to inform decisions about broadening this list in future:
   - report on intersection of:
      - CAP organList with major_organ_slim
      - CAP organList with organ_slim
      - CAP organLIst with subClasses of uberon:organ

**Comment by dosumis** [comment]
Questions about tissue_dict.json for @mfutey:

- How do the different types of term (general and specific) map to the annotation fields on CAP.   Are the general terms meant for the organ field and the more specific ones for tissue?
 
- What is the purpose of the mapping between the two types of term?  Is this to populate the organ field when more specific terms are chosen?
 
- Would it be useful to automatically suggest a general organ term from a more specific one? (we can do this via APIs over Uberon).

**Comment by evanbiederstedt** [comment]
@mfutey is the definitive resource here---I just got to this comment first; she'll follow up. 

> How do the different types of term (general and specific) map to the annotation fields on CAP. Are the general terms meant for the organ field and the more specific ones for tissue?

It's largely based on the UI for the faceted search. 

We would like to organize the terms given by users to be in "Broad organ categories". More specific terms would be organized under the broad categories. 

"""
- Brain
    - frontal lobe
    - parietal lobe
    - cerebellum
- Liver
    - Right hepatic duct
    - Hepatic artery
"""

I don't think we'll ever get users to agree on "what's a tissue" vs "what's an organ". 

Inevitably, if we don't do something here on our part in terms of data curation, the search facets will be a mess for the user. 

> Would it be useful to automatically suggest a general organ term from a more specific one? (we can do this via APIs over Uberon).

Yes, in terms of optimizing the ontology pipeline APIs, we should encourage the users to give us as specific of a term as possible.

**Comment by dosumis** [comment]
HI Evan,

> I don't think we'll ever get users to agree on "what's a tissue" vs "what's an organ".

Agreed. No one can.  But we can nudge towards some preferred groupings via:

(a) Boosting preferred groupings on autocomplete in organ field.
(b) Suggesting more general terms by mapping up from more specific ones. 
   -  I wonder if it would be better for this if the tissue field sits above the organ/grouping term field that way users are likely to fill it out first so we could use the choice to suggest an organ/grouping term.
   -  I'll get @ubyndr to work with one of our other devs to extend one of our existing APIs to support this.  Can have demo in place this week.  https://github.com/INCATools/ubergraph/issues/52

Looking at the list of general terms from @mfutey, I think some are still quite specific, so it might be worth working on a compromise list between this and the ones we already have in Uberon - testing this against use cases.  @bvarner-ebi can work on this when he gets back.

**Comment by evanbiederstedt** [comment]
Hi @dosumis 

Carrying on this conversation in Slack.

**Comment by ghost** [comment]
From @dosumis's [comment](https://github.com/kharchenkolab/cap-pipeline-config/issues/46#issuecomment-1108811266) above:

>Generate reports to inform decisions about broadening this list in future:
report on intersection of:
CAP organList with major_organ_slim
CAP organList with organ_slim
CAP organLIst with subClasses of uberon:organ

Kindly see [OrganList](https://docs.google.com/spreadsheets/d/1QzuB07M61TqCElRzydWVs4ap5RIIlmg7xIpSLxC6PFU/edit#gid=272982245) with some added and updated tabs. The tab titled "tissue_dict-uniqueCURIEs" shows intersections with the sets above. I look forward to feedback on this.

Spoiler: here are the general terms from [tissue_dict.json](https://github.com/kharchenkolab/cap-data-clean-up/blob/devel/datasets_description/tissue_dict.json) that intersect with all 3 sets noted above:

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

CURIE | LABEL
-- | --
UBERON:0001043 | esophagus
UBERON:0000948 | heart
UBERON:0002113 | kidney
UBERON:0002048 | lung
UBERON:0001264 | pancreas
UBERON:0002240 | spinal cord
UBERON:0000945 | stomach
UBERON:0000057 | urethra

</google-sheets-html-origin>

Of note, I'm surprised to not see 'brain' in the organ_slim.

**Comment by dosumis** [comment]
- [x]  Make sure Mary's [latest organ list]( https://github.com/kharchenkolab/cap-data-clean-up/blob/devel/datasets_description/organ_dict.json) (organs only) is completely mapped.
- [x] Make robot template to generate cap_organ_subset tags for this list of terms.  Build to test.  @dosumis  to provide recipe.
- [x] Robot template will live in new repo (see) https://github.com/kharchenkolab/cap-pipeline-config/issues/52
- [x] Add to triplestore loading config (GitHub raw URL) : https://github.com/kharchenkolab/cap-pipeline-config/blob/main/config/collectdata/vfb_fullontologies.txt
- [x] Update the script that updates the YAML config to point to our local knowledgeBase
- [x] Update the organ[ SPARQL query](https://github.com/kharchenkolab/cap-pipeline-config/blob/main/config/dumps/sparql/construct_Organ.sparql) to use this new subset

**Comment by ghost** [comment]
Related page regarding "organ list": https://capdevelopment.atlassian.net/wiki/spaces/~619bff5d6d002b006b63caae/pages/161939465/Organ+list

**Comment by ghost** [comment]
> - [x]  Make sure Mary's [latest organ list]( https://github.com/kharchenkolab/cap-data-clean-up/blob/devel/datasets_description/organ_dict.json) (organs only) is completely mapped.

[OrganList](https://docs.google.com/spreadsheets/d/1QzuB07M61TqCElRzydWVs4ap5RIIlmg7xIpSLxC6PFU/edit#gid=272982245) has been updated to align with [organ_dict.json](https://github.com/kharchenkolab/cap-data-clean-up/blob/devel/datasets_description/organ_dict.json) (formerly tissue_dict.json).

Changes I found in the current organ_dict.json compared to previous version (with respect to the general organ terms):

**Added terms:**
lymphatic system 

**Removed terms:**
blood cell
bone element
bone marrow
bronchus
bronchus (cell culture)
cerebellum
lymph
lymph node
lymphatic vessel
nasal cavity
peripheral lymph node

Note: terms may appear in the plural form in tissue_dict.json.

@mfutey, do the above findings match or seem reasonably aligned with the updates you made?

**Comment by mfutey** [comment]
Yes, these changes align with the recent updates.

**Comment by dosumis** [comment]
Template:

| ID | subset | label
| -- | -- | -- | 
| ID | AI oboInOwl:inSubset |  | 
| UBERON:0001043 | <slim_iri> | esophagus |

The final column is just for curator reference.  Keeping the second row blank ensures that this is not read by the template.

Note the oboInOwl Prefix is defined in the default PREFIX map used by ROBOT (https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/obo_context.jsonld#L4 - see http://robot.obolibrary.org/global#prefixes) 

TBD - IRI for slim.  We need to declare this as an Annotation Property.  This can be done in a small helper ontology. I think not strictly necessary for it to resolve.

**Comment by ghost** [comment]
> - [x] Make robot template to generate cap_organ_subset tags for this list of terms. Build to test. @dosumis to provide recipe.

@dosumis, @ubyndr, can you check if this makes sense for the template: https://docs.google.com/spreadsheets/d/1a4eetIYVerd1gu5piG7emi3n1gGD9T42sO27TwZ7lo4/edit#gid=0

**Comment by dosumis** [comment]
Closing this now we have a new process for generating and using a CAP organ slim.  Efforts to refine will now move to work with Juptyter notebooks - see https://capdevelopment.atlassian.net/browse/MVP-1628
